magick montage \
                $1-i-1-s-1 \
                null: \
                null: \
                null: \
                null: \
                null: \
                null: \
                $1-i-2-s-1 \
                $1-i-2-s-2 \
                null: \
                null: \
                null: \
                null: \
                null: \
                $1-i-3-s-1 \
                $1-i-3-s-2 \
                $1-i-3-s-4 \
                null: \
                null: \
                null: \
                null: \
                $1-i-4-s-1 \
                $1-i-4-s-2 \
                $1-i-4-s-4 \
                $1-i-4-s-8 \
                null: \
                null: \
                null: \
                $1-i-5-s-1 \
                $1-i-5-s-2 \
                $1-i-5-s-4 \
                $1-i-5-s-8 \
                $1-i-5-s-16 \
                null: \
                null: \
                $1-i-6-s-1 \
                $1-i-6-s-2 \
                $1-i-6-s-4 \
                $1-i-6-s-8 \
                $1-i-6-s-16 \
                $1-i-6-s-32 \
                null: \
                $1-i-7-s-1 \
                $1-i-7-s-2 \
                $1-i-7-s-4 \
                $1-i-7-s-8 \
                $1-i-7-s-16 \
                $1-i-7-s-32 \
                $1-i-7-s-64 \
    -geometry +8+8 -tile 7x7 pyramid-$1
